### ISSUE TITLE
Not working :( 

### ISSUE THREAD

**Issue by XamarinDeveloper** [eamileann/Ubuntu-boot-splash-colour-change#1]
Hey, I did all the steps and it's not working on ubuntu 18.04 :(

**Comment by michalpajtinka** [comment]
Hi, I will check what has changed for the Ubuntu 18.04 version and update the steps. I hope I will manage to find some time for that during this week :)

**Comment by XamarinDeveloper** [comment]
Sorry, It works, my bad :sweat_smile:
